module.exports = {
	billboard: {
		image: "图片",
		scale: "缩放",
		pixelOffset: "偏移量",
		horizontalOrigin: "水平对齐方式",
		verticalOrigin: "垂直对齐方式",
		color: "颜色",
		width: "宽度",
		height: "高度",
		scaleByDistance: "按距离缩放",
		translucencyByDistance: "按距离透明度",
		distanceDisplayCondition: "按距离显示",
		disableDepthTestDistance: "显示层级",
	},
	model: {
		gltf: "模型",
		scale: "缩放",
		minimumPixelSize: "最小尺寸",
		maximumScale: "最大比例",
		runAnimations: "动画播放",
		silhouetteColor: "外轮廓颜色",
		silhouetteSize: "外轮廓大小",
		color: "颜色",
		colorBlendMode: "颜色混合模式",
		colorBlendAmount: "颜色混合权重",
		distanceDisplayCondition: "按距离显示",
	},
	label: {
		text: "文本",
		font: "字体",
		style: "样式",
		scale: "缩放",
		showBackground: "背景",
		backgroundColor: "背景色",
		pixelOffset: "偏移量",
		horizontalOrigin: "水平对齐方式",
		verticalOrigin: "垂直对齐方式",
		fillColor: "字体颜色",
		outlineColor: "边线颜色",
		outlineWidth: "边线宽度",
		translucencyByDistance: "按距离透明度",
		scaleByDistance: "按距离缩放",
		distanceDisplayCondition: "按距离显示",
		disableDepthTestDistance: "显示层级",
	},
	point: {
		pixelSize: "大小",
		color: "颜色",
		outlineColor: "外边线颜色",
		outlineWidth: "外边线宽度",
		scaleByDistance: "按距离缩放",
		translucencyByDistance: "按距离透明度",
		distanceDisplayCondition: "按距离显示",
		disableDepthTestDistance: "显示层级",
	},
	polyline: {
		positions: "端点",
		width: "线宽",
		material: "材质",
		distanceDisplayCondition: "按距离显示",
	}
}