module.exports = {
	billboard: {
		image: "Image",
		scale: "Scale",
		pixelOffset: "Pixel Offset",
		horizontalOrigin: "Horizontal Origin",
		verticalOrigin: "Vertical Origin",
		color: "Color",
		width: "Width",
		height: "Height",
		scaleByDistance: "Scale By Distance",
		translucencyByDistance: "Translucency By Distance",
		distanceDisplayCondition: "Distance Display Condition",
		disableDepthTestDistance: "Disable Depth Test Distance",
	},
	model: {
		gltf: "Model",
		scale: "Scale",
		minimumPixelSize: "Minimum Pixel Size",
		maximumScale: "Maximum Scale",
		runAnimations: "Run Animations",
		silhouetteColor: "Silhouette Color",
		silhouetteSize: "Silhouette Size",
		color: "Color",
		colorBlendMode: "Color Blend Mode",
		colorBlendAmount: "Color Blend Amount",
		distanceDisplayCondition: "Distance Display Condition",
	},
	label: {
		text: "Text",
		font: "Font",
		style: "Style",
		scale: "Scale",
		showBackground: "Show Background",
		backgroundColor: "Background Color",
		pixelOffset: "Pixel Offset",
		horizontalOrigin: "Horizontal Origin",
		verticalOrigin: "Vertical Origin",
		fillColor: "Fill Color",
		outlineColor: "Outline Color",
		outlineWidth: "Outline Width",
		translucencyByDistance: "Translucency By Distance",
		scaleByDistance: "Scale By Distance",
		distanceDisplayCondition: "Distance Display Condition",
		disableDepthTestDistance: "Disable Depth Test Distance",
	},
	point: {
		pixelSize: "Pixel Size",
		color: "Color",
		outlineColor: "Outline Color",
		outlineWidth: "Outline Width",
		scaleByDistance: "Scale By Distance",
		translucencyByDistance: "Translucency By Distance",
		distanceDisplayCondition: "Distance Display Condition",
		disableDepthTestDistance: "Disable Depth Test Distance",
	},
	polyline: {
		positions: "Positions",
		width: "Width",
		material: "Material",
		distanceDisplayCondition: "Distance Display Condition",
	}
}